### ISSUE TITLE
Error in data[[rlabp]] : subscript out of bounds - Tax4Fun

### ISSUE THREAD

**Issue by emankhalaf** [nick-youngblut/Tax4Fun#1]
Hello,
I am using SILVAngs for rDNA-based microbial community analysis. When importing the csv file (as in Tax4Fun) turorial:
importSilvaNgsData(inputFiles = "silk_mb---ssu---fingerprint----Total---sim_93---tax_silva---td_20.csv")
I got this error :
Error in data[[rlabp]] : subscript out of bounds

May any of you please help me. 
Thanks

**Comment by nick-youngblut** [comment]
@emankhalaf this is essentially just a "fork" of the SourceForge code. You should contact the developers there.

**Comment by emankhalaf** [comment]
I did contacted them two weeks ago with no response.

**Comment by nick-youngblut** [comment]
Yeah, the original project seems to be more or less abandoned. Your error appears to be due to a key error for the list object, but I have no idea why. Maybe you are missing something (eg., a required column) in your input file?

**Comment by emankhalaf** [comment]
It should be straight forward as I am using the output of SILVAngs. It is really weird. I found a suggested solution in researchgate, https://www.researchgate.net/post/Using_Tax4Fun_in_R_Subscript_out_of_bounds_Why
but I am not convinced with the steps. I tried part of it by adding an index column, but it did not work as well.

**Comment by nitschkematthew** [comment]
@emankhalaf did you get it to work? I have been using Tax4Fun recently on Qiime outputs with success. Let me know I can help you.

**Comment by emankhalaf** [comment]
Not yet, depressed. Am using the output file of SILVAngs which one of the potential options in Tax4Fun tutorial???
I really need help.
Thanks

**Comment by nitschkematthew** [comment]
In my instance I was uploading a .tsv file output from Qiime. I would suggest making a mini dataset of your output from SILVAngs. 2 or 3 samples. 5 to 10 OTUs.

For the .tsv import function, it expects that it should discard the first row (this is because the BIOM format package adds an extra row above with "# Constructed from biom file" when it converts from .biom to .tsv). If this extra row is not there, the import function will discard your sample names. Not good. Perhaps something similar is happening in your instance?

If you look at the source code of the import function using,

`getAnywhere(importSilvaNgsDataFile)`

you can see that the function will skip the first row of your input and start from there. Let me know if this is a step in the right direction.

**Comment by emankhalaf** [comment]
I contacted the package developers, and they deleted the column name of the tax column, and now it is working.
Thanks for your interest.
Eman

**Comment by emankhalaf** [comment]
I found weird results, is it possible to find pathways related to human body such as Alzheimer disease from samples of plant-associated microbes???

**Comment by nitschkematthew** [comment]
Yes it is possible. I think Tax4Fun returns KEGG pathways even if you only have a single ortholog of the reference pathway.

**Comment by emankhalaf** [comment]
Good to know. Are you using STAMP for visualizing Tax4Fun output. That is what I found in other forums.

**Comment by emankhalaf** [comment]
Also, I have a primitive question, the structure of Tax4Fun pathway table is like that:
dna-sequences1
ko00010; Glycolysis / Gluconeogenesis	0.00889085528233458
ko00020; Citrate cycle (TCA cycle)	0.00630111153652855
ko00030; Pentose phosphate pathway	0.00875885645192426


and that of function table is as follow:
dna-sequences1
K00001; alcohol dehydrogenase [EC:1.1.1.1]	0.000608817946097947
K00002; alcohol dehydrogenase (NADP+) [EC:1.1.1.2]	6.36445483660783e-06
K00003; homoserine dehydrogenase [EC:1.1.1.3]	0.000633081574008416

what are ko0000/k00000? and what about the fractions on the other side (are they abundance of that pathway/functional gene?

How can I correlate these results with my samples?
BY the way, I repeated the analysis using sub-set of my samples and I got the same results. I feel like this displayed results are default output including all KEGG database, is not?

**Comment by emankhalaf** [comment]
I found same functions but with different values (abundances) in different datasets.

**Comment by nitschkematthew** [comment]
If you go to the KEGG website you can find reference to each of those KXXXXXX values.
Tax4Fun computes the composite metagenome on a per-sample basis. Not as a relative porportion across the whole dataset of samples.
STAMP would work! Or Multtest!

**Comment by emankhalaf** [comment]
Oh thanks, got it.
You mean it deals with a single file of sequences (merged sequences for a group of samples) as a single sample.
I think that is good if I have control samples and pathogen-treated samples, so I can merge sequences of each group as a single file and apply Tax4Fun. So, I would be able to compare functional/metabolic activity of each group (health vs disease)!

**Comment by nitschkematthew** [comment]
Why would your control and treatment files be separate? If you have analysed these two groups separately in SilvaNGS then this will present some problems as two OTU tables cannot be compared/merged easily.

**Comment by emankhalaf** [comment]
I have the whole project as one OTU-table and one seq.fna file, but when applied SILVAngs then Tax4Fun, I could not be able to distinguish between metabolic profile of healthy samples and diseased ones. As you mentioned, tax4Fun deals with sequence file as a single sample. So, I thought about re-do but using control samples file vs pathogen-treated file. Then I can pick up genes and pathways of interest from the output with their corresponding values for each group, then use these results in STAMP for statistical analysis.
Is that correct?

**Comment by nitschkematthew** [comment]
If you cannot see any difference between diseased and healthy samples then splitting them into separate files will not change anything. You will still get the same KEGG profiles back for each sample.

One thing to check is your tax4fun$FTU values that are output from Tax4Fun. This is the fraction of silva assigned OTUs that are not found in the KEGG organism database. These are not inferred and do not contribute to your metagenomic profile. If these FTU values are large, there is a good chance that the bacteria that are unique to one sample type and distinguish between healthy and diseased samples are not in the database. In this case your profiles will be identical because you are only computing the metagenome for the bacteria that are common between the two sample types.

**Comment by emankhalaf** [comment]
I think I have something missing in my code. May you please take a look on the following code and let me know. By the way, the output file from SILVAngs just includes no. of taxa for each taxonomic path. No information about samples id. So, how can I include the sample ids in my code??? How can I correlate the functions/pathways with samples???
DATA = importSilvaNgsData('microbiome---ssu---fingerprint----Total---sim_93---tax_silva---td_20.csv')

FUNC = Tax4Fun(Tax4FunInput = DATA, folderReferenceData = 'SILVA123/')

write.table(x = t(FUNC$Tax4FunProfile), file = "microbiome---ssu---fingerprint----Total---sim_93---tax_silva---td_20_func.txt", append = F, quote = F, sep = "\t", row.names = T, col.names = T)

PATHWAY = Tax4Fun(Tax4FunInput = DATA, folderReferenceData = 'SILVA123/', fctProfiling = F)

head(PATHWAY)
I got this:
$Tax4FunProfile
               ko00010; Glycolysis / Gluconeogenesis ko00020; Citrate cycle (TCA cycle) ko00030; Pentose phosphate pathway
dna-sequences1                           0.008890855                        0.006301112                        0.008758856
 long list of pathways            

head(FUNC)

I got this:
$Tax4FunProfile
               K00001; alcohol dehydrogenase [EC:1.1.1.1] K00002; alcohol dehydrogenase (NADP+) [EC:1.1.1.2]
long list of genes

**Comment by emankhalaf** [comment]
I think should be in their corresponding values. I split the samples but based on sample location. I can see the same list of genes and pathways, but in different values. So, my suggestion is to split sequences based on treatment and find the differences in the corresponding values.
Do I understand the technique well.

**Comment by nitschkematthew** [comment]
This file that you are importing here, what does this file consist of? Is this just data for a single sample? 

`DATA = importSilvaNgsData('microbiome---ssu---fingerprint----Total---sim_93---tax_silva---td_20.csv')`

If you want I can send you a small fake dataset to test the Tax4fun output and so you can understand what the import file should look like. My email is on my github profile. To get the FTU values I was mentioning before

`FUNC$FTU`

**Comment by emankhalaf** [comment]
No, it includes sequences of the whole samples. I have large number of samples and it would not be helpful to import sample by sample. That is why I am suggesting to deal with control samples and the treatment group separately, then compare the values for the same genes in each output

**Comment by nitschkematthew** [comment]
If you want to do it that way that would work but Tax4Fun is fast and there doesnt seem to be much point to splitting them during the analysis step.

You still have not answered my question about the FTU values.

**Comment by emankhalaf** [comment]
So, the statistics should be done on FTU values or on the corresponding values for each pathway/gene which should be different from sample to another.
Which is more important ftu values or these numbers displayed at each gene in the output??? Also, what does this number indicate, is it the abundance(weight) of that gene/pathway in the sample?

**Comment by ltalluto** [comment]
We have experienced the same problem, and it looks to be a bug in Tax4Fun in the way it assigns row names to the OTU table. I've written a fix that seems to be working, if desired I can submit a pull request once we know for sure that it is working.

**Comment by wanglu2014** [comment]
> 
> 
> We have experienced the same problem, and it looks to be a bug in Tax4Fun in the way it assigns row names to the OTU table. I've written a fix that seems to be working, if desired I can submit a pull request once we know for sure that it is working.

Highly desired. Your help will help us so much!

**Comment by ltalluto** [comment]
@wanglu2014 Done; you can also get the commit from my fork while it lasts. Hope it works for you!

**Comment by wanglu2014** [comment]
> 
> 
> @wanglu2014 Done; you can also get the commit from my fork while it lasts. Hope it works for you!

Thank for your kindly fix. I feel so excited and happily tried. the import problem is successfully solved. However the 'length of 'dimnames' [1] not equal to array extent' problem happens. Even a mini test file , which cut 100otus from original Tax4fun test is failed, too.
Thanks for your efforts!
[HMP_0.97_tablemini.txt](https://github.com/nick-youngblut/Tax4Fun/files/3378319/HMP_0.97_tablemini.txt)
code:
silva_ngs_table<-importSilvaNgsData("G:/CIcopy - Copy/CI/basic source/skin/Tax4Fun/HMP_0.97_tablemini.txt")
c=silva_ngs_table$otuTable
Tax4Fun(silva_ngs_table,"G:/CIcopy - Copy/CI/basic source/skin/Tax4Fun/SILVA123",fctProfiling = TRUE,refProfile ="UProC",shortReadMode=TRUE,normCopyNo = TRUE)
