### ISSUE TITLE
Error in dimnames(x) <- dn : length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by wanglu2014** [nick-youngblut/Tax4Fun#2]
![图片](https://user-images.githubusercontent.com/12541282/57387459-f21f4e00-71e8-11e9-8623-03647818e6ba.png)
Could you kindly dignose this cause of error?

**Comment by wanglu2014** [comment]
even add into 7 elements, there is still a error~
Bacteria;   Firmicutes; Clostridia; Clostridiales; Christensenellaceae; uncultured;   uncultured bacterium

**Comment by nick-youngblut** [comment]
@wanglu2014 I don't understand the error. Also, I'm not actually the developer of Tax4Fun. This github repo is really just for creating the bioconda package. You should contact the developer directly: http://tax4fun.gobics.de/

**Comment by wanglu2014** [comment]
Thanks
